In [11]:
# Code to calculate the mismatch error rate

import numpy as np

# Array of MAR values
frame_values = np.random.rand(50, 6)
frame_values = np.round(frame_values, 2)
print(frame_values)

# Array of frame classification values| 1: open, 0: closed
frame_values[frame_values >= 0.6] = 1
frame_values[frame_values < 0.6] = 0

# Create an empty 1D NumPy array with the same number of rows as frame_values
classification = np.ones(frame_values.shape[0], dtype=int)
    
# Iterate over the rows of the array
for i in range(frame_values.shape[0]):
    # Check if the row contains any 0s
    if 0 in frame_values[i]:
        classification[i] = 0
    
print(classification)

# Calculate the percentage of 1's in the array
num_zeros = np.sum(classification == 1)
mismatch = (num_zeros / len(classification)) * 100
    
print(f"Mismatch of the Frames: {mismatch:.2f}%")

[[0.95 0.59 0.33 0.36 0.64 0.49]
 [0.19 0.36 0.57 0.35 0.35 0.1 ]
 [0.19 0.09 0.84 0.96 0.34 0.52]
 [0.54 0.3  0.11 0.17 0.09 0.74]
 [0.31 0.58 0.21 0.85 0.06 0.1 ]
 [0.84 0.54 0.63 0.57 0.4  0.81]
 [0.65 0.39 0.79 0.65 0.13 0.1 ]
 [0.6  0.99 0.32 0.77 0.44 0.49]
 [0.52 0.69 0.11 0.05 0.11 0.64]
 [0.59 0.23 0.39 0.27 0.22 0.25]
 [0.16 0.91 0.96 0.67 0.42 0.29]
 [0.45 0.17 0.98 0.97 0.15 0.44]
 [0.9  0.64 0.03 0.59 0.82 0.77]
 [0.36 0.29 0.02 0.54 0.18 0.21]
 [0.28 0.9  0.52 0.85 0.54 0.15]
 [0.97 0.54 0.7  0.71 0.62 0.3 ]
 [0.34 0.76 0.11 0.74 0.93 0.89]
 [0.81 0.35 0.6  0.64 0.19 0.25]
 [0.2  0.07 0.75 0.77 0.14 1.  ]
 [0.93 0.72 0.15 0.39 0.12 0.95]
 [0.2  0.98 0.42 0.86 0.93 0.45]
 [0.49 0.78 0.17 0.33 0.38 0.41]
 [0.02 0.43 0.11 0.77 0.19 0.09]
 [0.36 0.2  0.27 0.74 0.21 0.02]
 [0.95 0.4  0.94 0.55 0.95 0.3 ]
 [0.26 0.52 0.4  0.48 0.74 0.91]
 [0.27 0.86 0.79 0.97 0.21 0.45]
 [0.52 0.7  0.01 0.94 0.86 0.52]
 [0.55 0.15 0.01 0.13 0.2  0.51]
 [0.84 0.89 0.47 0.11 0.89 0.78]
 [0.98 0.4