In [7]:
# Code to calculate the mismatch error rate

import numpy as np

# Array of MAR values
frame_values = np.random.rand(20, 6)
frame_values = np.round(frame_values, 2)
print(frame_values)

# Array of frame classification values| 0: open, 1: closed
frame_values[frame_values >= 0.6] = 1
frame_values[frame_values < 0.6] = 0

# Create an empty 1D NumPy array with the same number of rows as frame_values
classification = np.zeros(frame_values.shape[0], dtype=int)
    
# Iterate over the rows of the array
for i in range(frame_values.shape[0]):
    # Check if the row contains any 1s
    if np.sum(frame_values[i]) > 0:
        classification[i] = 1
    
print(classification)

# Calculate the percentage of 0's in the array
num_zeros = np.sum(classification == 0)
mismatch = (num_zeros / len(classification)) * 100
    
print(f"Mismatch of the Frames: {mismatch:.2f}%")

[[0.2  0.36 0.64 0.49 0.72 0.02]
 [0.5  0.11 0.1  1.   0.46 0.11]
 [0.14 0.28 0.5  0.46 0.4  0.55]
 [0.2  0.41 0.06 0.88 0.99 0.38]
 [0.74 0.62 0.26 0.43 0.23 0.22]
 [0.37 0.36 0.68 0.62 0.06 0.83]
 [0.36 0.9  0.78 0.52 0.85 0.83]
 [0.54 0.07 0.72 0.93 0.22 0.63]
 [0.2  0.96 0.7  0.03 0.48 0.65]
 [0.17 0.07 0.34 0.07 0.41 0.95]
 [0.89 0.24 0.37 0.22 0.41 0.9 ]
 [0.55 0.41 0.04 0.9  0.3  0.35]
 [0.75 0.97 0.95 0.65 0.97 0.64]
 [0.8  0.19 0.32 0.12 0.71 0.16]
 [0.43 0.44 0.38 0.79 0.1  0.61]
 [0.77 0.22 0.89 0.25 0.04 0.08]
 [0.41 0.67 0.75 0.66 0.2  0.11]
 [0.1  0.81 0.63 0.46 0.63 0.18]
 [0.04 0.26 0.29 0.6  0.92 0.78]
 [0.9  0.59 0.73 0.08 0.05 0.59]]
[1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Mismatch of the Frames: 5.00%
